// Generated by CoffeeScript 1.3.3

/*
# to minify: 
java -jar /usr/local/closure-compiler/compiler.jar \
  --compilation_level SIMPLE_OPTIMIZATIONS \
  --js github-widget.js \
  --js_output_file github-widget.min.js
*/


(function() {
  var go, tag,
    __hasProp = {}.hasOwnProperty;

  go = function() {
    var callback, div, head, i, url, user, _i, _len, _ref, _results;
    head = document.getElementsByTagName('head')[0];
    _ref = document.getElementsByTagName('div');
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      div = _ref[i];
      if (div.className !== 'github-widget') {
        continue;
      }
      user = div.getAttribute('data-user');
      callback = "githubWidgetJSONPCallback_" + i;
      window[callback] = (function(div, user) {
        return function(payload) {
          var repo, repoOuterTag, repoTag, siteRepoName, statsTag, titleTag, _j, _len1, _ref1, _results1;
          tag({
            className: 'gw-clearer',
            prevSibling: div
          });
          siteRepoName = "" + user + ".github.com";
          _ref1 = payload.data.sort(function(a, b) {
            return b.watchers - a.watchers;
          });
          _results1 = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            repo = _ref1[_j];
            if (repo.fork || repo.name === siteRepoName || !(repo.description != null) || repo.description === '') {
              continue;
            }
            repoOuterTag = tag({
              className: 'gw-repo-outer',
              parent: div
            });
            repoTag = tag({
              className: 'gw-repo',
              parent: repoOuterTag
            });
            titleTag = tag({
              className: 'gw-title',
              parent: repoTag
            });
            statsTag = tag({
              name: 'ul',
              className: 'gw-stats',
              parent: titleTag
            });
            tag({
              name: 'a',
              href: repo.html_url,
              text: repo.name,
              className: 'gw-name',
              parent: titleTag
            });
            tag({
              name: 'li',
              text: "" + repo.watchers,
              className: 'gw-watchers',
              parent: statsTag
            });
            tag({
              name: 'li',
              text: "" + repo.forks,
              className: 'gw-forks',
              parent: statsTag
            });
            if (repo.language != null) {
              tag({
                className: 'gw-lang',
                text: repo.language,
                parent: repoTag
              });
            }
            _results1.push(tag({
              text: repo.description,
              className: 'gw-repo-desc',
              parent: repoTag
            }));
          }
          return _results1;
        };
      })(div, user);
      url = "https://api.github.com/users/" + user + "/repos?callback=" + callback;
      _results.push(tag({
        name: 'script',
        src: url,
        parent: head
      }));
    }
    return _results;
  };

  tag = function(opts) {
    var k, t, v, _ref;
    t = document.createElement((_ref = opts.name) != null ? _ref : 'div');
    for (k in opts) {
      if (!__hasProp.call(opts, k)) continue;
      v = opts[k];
      switch (k) {
        case 'name':
          continue;
        case 'parent':
          v.appendChild(t);
          break;
        case 'prevSibling':
          v.parentNode.insertBefore(t, v.nextSibling);
          break;
        case 'text':
          t.appendChild(document.createTextNode(v));
          break;
        default:
          t[k] = v;
      }
    }
    return t;
  };

  if (document.addEventListener) {
    document.addEventListener('DOMContentLoaded', go, false);
  } else if (window.attachEvent) {
    window.attachEvent('onload', go);
  }

}).call(this);
